site_name: Informationen Fachbereich Informatik
site_url: "https://fb.informatik.sg"
repo_url: "https://github.com/gbssg/fb"
edit_uri: "blob/main/docs/"

nav:
  - Willkommen: index.md
  - Allgmeine Informationen:
    - Modulinformationen: 1-10.md
    - Leistungsbeurteilungsvorgaben (LBV): 1-20.md
    - Lizenzen: 1-30.md
    - BYOD: 1-40.md
    - Weiterführende Links: 1-50.md
  - Informatiker EFZ:
    - Applikations- und Plattformentwicklung: 2-10.md
  - ICT-Fachfrau/-mann EFZ:
    - Informationen: 3-10.md
  - Entwickler/in digitales Business EFZ:
    - Aktueller Stand: 4-10.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  features:
    - navigation.instant
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2023 <a href='https://www.gbssg.ch'><span style='font-weight:1000'>gbs</span>sg.ch</a> <span class='green'>|</span> Informatik <span class='green'>|</span> Informationen
extra:
  social:
    - icon: material/home
      link: https://www.gbssg.ch
      name: gbssg.ch
