site_name: Modul 346 - Cloudlösungen konzipieren und realisieren
site_url: "https://oliverlux.github.io/modul346"
repo_url: "https://github.com/gbssg/m346"
edit_uri: "blob/main/docs/"

nav:
  - 0. Übersicht: index.md
  - 1. Begrifflichkeiten:
    - Cloud Computing: 1-10.md
    - Betriebsmodelle: 1-20.md
    - Hyperscaler: 1-30.md
    - Computer-Optionen: 1-40.md
  - 2. Cloud Services:
    - Speicherung Hauptdatentypen: 2-10.md
    - Verantwortlichkeiten Cloud Services: 2-20.md
  - 3. Netzwerkkonzept:
    - virtuelle private Cloud: 3-10.md
    - Anbindungsmöglichkeiten: 3-20.md
    - Routing: 3-30.md
    - Netzwerksicherheit: 3-40.md
  - 4. Hyperscaler:
    - Infrastruktur: 4-10.md
    - Best Practices: 4-20.md
    - Informationsquellen (Referenzarchitekturen, Security Dokumentation): 4-30.md
  - 5. Cloudmigration:
    - Kostenmodelle, Kostenanalysen: 5-10.md
    - Lift-and-Shift, Lift-and-Reshape: 5-20.md
    - Begrifflichkeiten (Verfügbarkeit, Datensicherheit und -resilienz, Hochverfügbarkeit, Disaster Recovery und Backup): 5-30.md
    - Entwicklung einer einfachen Gesamtarchitektur, Definition von relevanten Cloud-Services: 5-40.md
    - Testkonzept zur Überprüfung von Funktionalität, Performance und Sicherheit: 5-50.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  features:
    - navigation.instant
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2021 <a href='https://www.gbssg.ch'><span style='font-weight:1000'>gbs</span>sg.ch</a> <span class='green'>|</span> Informatik <span class='green'>|</span> Modul 346
extra:
  social:
    - icon: material/home
      link: https://www.gbssg.ch
      name: gbssg.ch
